<?php


namespace App\Repositories;

use App\Models\User;
use App\Repositories\BaseRepository;

class UserRepository extends BaseRepository
{
    public function __construct(User $entity)
    {
        $this->entity = $entity;
    }

    public function destroy(int $id)
    {
        $entity = $this->getById($id);
        if($entity && $entity->id == auth()->user()->id)
            abort(400, "You can't turn yourself off");

        return parent::destroy($id); // TODO: Change the autogenerated stub
    }
}
